### ISSUE TITLE
Yarn build not working on v2.5.0

### ISSUE THREAD

**Issue by Today20092** [linkwarden/linkwarden#502]
**Describe the bug**
Yarn build does not work.

```sh
yarn build
yarn run v1.22.21
$ next build
- info Loaded env from /opt/linkwarden/.env
- info Linting and checking validity of types ...Failed to compile.

./components/CollectionListing.tsx:36:17
Type error: Property 'collectionOrder' does not exist on type 'AccountSettings'.

  34 |         collections,
  35 |         router,
> 36 |         account.collectionOrder
     |                 ^
  37 |       );
  38 |     }
  39 |     return undefined;
error Command failed with exit code 1.
```

**To Reproduce**
In shell `/opt/linkwarden`

1. git pull
2. yarn
3. npx playwright install-deps
4. yarn build

**Expected behavior**
Linkwarden to build then follow the next upgrading comand:

`yarn prisma migrate deploy`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian GNU
 - Version: Linux 12 (bookworm)

**Additional context**
Used [Proxmox Helper Script ](https://github.com/tteck/Proxmox/blob/321660487de3d1df302c47e0ba21a999db28020b/ct/linkwarden.sh)first, then tried to do manually.

**Comment by daniel31x13** [comment]
Someone encountered the exact issue on the Discord server and managed to resolve it:
![image](https://github.com/linkwarden/linkwarden/assets/93432314/2c15a9e4-e2f2-406c-b094-3a9b571b9c66)

Also have you ran `yarn prisma generate`?

**Comment by Today20092** [comment]
> Also have you ran yarn prisma generate?
yes this seem to have worked. Thank you.
